#Source for Template: https://github.com/actions/upload-pages-artifact?tab=readme-ov-file#usage

name: Build Pages
on:
    push:
        branches:
        - main
    workflow_dispatch:


permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'  # Specify your .NET version here

      - name: Setup Build Environment
        run: |
          #dotnet workload install wasm-tools
          dotnet workload restore
      - name: Build static files
        id: build
        continue-on-error: true
        run: |
           #dotnet add package Winforms.Wasm 
           dotnet build . --configuration Release
           dotnet publish . --configuration Release

           #debug
           $filePathExe = Get-ChildItem -Path . -Recurse -Filter "OuterWeightApp_WinForms.exe" -ErrorAction SilentlyContinue

           if ($filePathExe) {
             Write-Host "Found EXE File at: $($filePathExe.FullName)"
           } else {
             Write-Host "EXE not found."
           }


           git clone https://github.com/sounddrill31/WinAppRunner
           # Zip the contents of bin/Release/net6.0-windows/

           
           Compress-Archive -Path ".\bin\Release\net481\publish\*" -DestinationPath ".\WinAppRunner\OuterWeightApp_WinForms.zip"
           (Get-Content ".\WinAppRunner\WinAppRunner.htm") -replace 'var exeDefault = "notepad.exe";', 'var exeDefault = "OuterWeightApp_WinForms.exe";' | Set-Content ".\WinAppRunner\WinAppRunner.htm"

           # Debug

           $filePath = Get-ChildItem -Path . -Recurse -Filter "index.html" -ErrorAction SilentlyContinue

           if ($filePath) {
             Write-Host "Found index.html at: $($filePath.FullName)"
           } else {
             Write-Host "index.html not found."
           }

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: WinAppRunner/

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
